# Generated by Django 3.0.2 on 2020-02-13 15:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200211_1617'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expensescategory',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='expenses',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='expensescategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
