# Generated by Django 3.0.2 on 2020-02-15 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0003_auto_20200213_2049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensescategory',
            unique_together={('title', 'user_id')},
        ),
    ]
